#spring:
#    datasource:
#      url: jdbc:h2:mem:testdb
#    jpa:
#      show-sql: true
#    data:
#      rest:
#        basePath: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cardb?serverTimezone=Asia/Seoul
    username: jason
    password: jason1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create #update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

  data:
    rest:
      basePath: /api